[project]
name = "psai-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipython>=8.37.0",
    "numpy>=2.2.6",
    "scikit-learn>=1.7.0",
]
